# Generated by Django 5.0.2 on 2024-11-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_api', '0002_alter_coursedescription_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedescription',
            name='image',
            field=models.ImageField(default='null', upload_to='CourseImage/'),
        ),
    ]
